version: '3.8'

services:
  service1-nodejs:
    build: ./microservices/service1-nodejs
    ports:
      - "3000:3000"
    networks:
      - app-network

  service2-python:
    build: ./microservices/service2-python
    ports:
      - "5000:5000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - service1-nodejs
      - service2-python
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
