- hosts: web
  become: yes
  tasks:
    - name: Install updates
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Copy Docker Compose file
      template:
        src: roles/docker/templates/docker-compose.yml.j2
        dest: /home/ubuntu/docker-compose.yml

    - name: Deploy Microservices with Docker Compose
      command: docker-compose -f /home/ubuntu/docker-compose.yml up -d
